global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:3000"]

  - job_name: "collector-fb"
    static_configs:
      - targets: ["collector-fb:3001"]

  - job_name: "collector-ttk"
    static_configs:
      - targets: ["collector-ttk:3002"]

  - job_name: "reporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["reporter:3003"]
