FROM node:18-alpine
RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./

COPY ./libs/db/prisma/schema.prisma ./prisma/schema.prisma

RUN npm install

RUN npx prisma generate --schema=./prisma/schema.prisma

COPY . .

CMD ["npm", "run", "start:dev"]