FROM node:20

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY apps/collector-fb/package*.json ./
COPY apps/collector-fb ./
COPY libs/db/prisma/schema.prisma ./prisma/schema.prisma

RUN npm install

RUN npx prisma generate --schema=./prisma/schema.prisma

CMD ["npm", "run", "start:dev"]
