FROM node:20

WORKDIR /app

COPY apps/collector-fb/package*.json ./
COPY apps/collector-fb ./
COPY libs/db/prisma/schema.prisma ./prisma/schema.prisma

RUN npm install

RUN npx prisma generate --schema=./prisma/schema.prisma

CMD ["npm", "run", "start:dev"]
