FROM node:18-alpine

WORKDIR /app

COPY apps/collector/package*.json ./apps/collector/
COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /app/apps/collector

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
