FROM node:20

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY apps/collector-ttk/package*.json ./

COPY ./libs/db/prisma/schema.prisma ./prisma/schema.prisma

RUN npm cache clean --force && rm -rf node_modules package-lock.json
RUN npm install

COPY apps/collector-ttk .

RUN npx prisma generate --schema=./prisma/schema.prisma

CMD ["npm", "run", "start:dev"]