FROM node:18-alpine

WORKDIR /app

COPY apps/collector-ttk/package*.json ./apps/collector-ttk/
COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /app/apps/collector-ttk

EXPOSE 3002

CMD ["npm", "run", "start:dev"]
