FROM node:20

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

COPY ./libs/db/prisma/schema.prisma ./prisma/schema.prisma

RUN npm cache clean --force && \
    rm -rf node_modules && \
    rm -f package-lock.json && \
    npm install --legacy-peer-deps

    
COPY apps/reporter/ .
    
RUN npx prisma generate --schema=./prisma/schema.prisma

EXPOSE 3003

CMD ["npm", "run", "start:dev"]
