version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: universe-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: universe
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d universe"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/universe
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:3000/health/liveness"]
      interval: 10s
      timeout: 5s
      retries: 5

  publisher:
    image: andriiuni/events
    platform: linux/arm64
    depends_on:
      gateway:
        condition: service_healthy
    environment:
      - EVENT_ENDPOINT=http://gateway:3000/events

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - nats-data:/data
    command: ["-c", "/etc/nats/nats-server.conf"]
    restart: always

volumes:
  postgres-data:
  nats-data:
