FROM node:18-alpine

WORKDIR /app

COPY apps/gateway/package*.json ./apps/gateway/

COPY package*.json ./

RUN npm install

COPY . .

WORKDIR /app/apps/gateway

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
