FROM node:20

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm cache clean --force && \
    rm -rf node_modules && \
    rm -f package-lock.json && \
    npm install --legacy-peer-deps
    
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
