FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl openssl

COPY package.json .

RUN npm install --omit=dev

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["node", "dist/main.js"]