FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && \
    rm -rf node_modules && \
    rm -f package-lock.json && \
    npm install --legacy-peer-deps
    
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
